---
# Ensure there's an EC2 instance running
# From http://docs.ansible.com/guide_aws.html

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision a set of instances
      ec2:
         key_name: scaladeployer-key-pair-ireland
         group: scaladeployer-sg-ireland
         region: eu-west-1
         instance_type: t2.micro
         # Ubuntu Server 14.04 LTS (HVM), SSD Volume Type
         image: ami-f0b11187
         wait: true
         exact_count: 1
         count_tag: class
      register: ec2
