---

- name: Set up base EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - ec2base

- name: Install Java and Scala
  hosts: ec2hosts
  user: ubuntu
  sudo: true
  sudo_user: root
  gather_facts: true

  roles:
    - smola.java
