---

- name: Set up base EC2 instances
  # Don't forget to have your AWS credentials available
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - ec2base

#- name: Install Java and Scala
#  hosts: ec2hosts
#  user: ubuntu
#  sudo: true
#  sudo_user: root
#  gather_facts: true
#
#  roles:
#    - azavea.scala
#
#- name: Start web server
#  hosts: ec2hosts
#  user: ubuntu
#  sudo: true
#  sudo_user: root
#  roles:
#    - webserver

- name: Get the web app up and running
  hosts: ec2hosts
  user: ubuntu
  sudo: false
  roles:
    - webapp
